In [1]:
# NumPy Basics & Fundamentals

# This notebook covers the core concepts of NumPy, including array creation, multi-dimensional structures (1D, 2D, and 3D), indexing, slicing, data types (dtypes), floating-point precision, and Boolean masking.

In [2]:
import numpy as np   #Imports the NumPy library with the 'np' alias

In [3]:
arr=np.array(19) #defines 0D-Skalar array
print(arr)
print(type(arr))
print(arr.ndim) #checks array dimension 

19
<class 'numpy.ndarray'>
0


In [4]:
arr1=np.array([21,13,8,4,9]) #Creates a 1D NumPy array
print(arr1)
print(arr1.ndim) #checks array dimension 

[21 13  8  4  9]
1


In [5]:
arr2=np.array([[1,2,3],[4,5,6]]) #Creates a 2D-Matrix NumPy array (2*3)
print(arr2)
print(type(arr2))
print(arr2.ndim) #checks array dimension 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [6]:
arr3=np.array([[[1],[2]],[[1],[2]],[[1],[2]]]) #Creates a 3D-Tensor NumPy array 
print(arr3)
print(arr3.ndim) #checks array dimension 

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]]
3


In [7]:
arr4=np.array([4,5,6,7],ndmin=7) #Creates a NumPy array with a minimum of 7 dimension
print("Number of Dimension",arr4.ndim)
print(arr4)

Number of Dimension 7
[[[[[[[4 5 6 7]]]]]]]


In [8]:
my_array=np.arange(1,20,3) # Creates an array of numbers from 1 up to 20 with a step size of 3
print(my_array)

[ 1  4  7 10 13 16 19]


In [9]:
my_array1=np.zeros((2,4)) # Creates a 2x4 matrix filled with zeros
print(my_array1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
my_array2=np.ones((4,3)) # Creates a 4x3 matrix filled with ones
print(my_array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
my_array5=np.full((2,3),5) # Creates a 2x3 matrix filled with the value 5
print(my_array5)

[[5 5 5]
 [5 5 5]]


In [12]:
my_array6=np.empty((2,2)) # Creates an uninitialized 2x2 matrix with random memory values
print(my_array6)

[[0. 0.]
 [0. 0.]]


In [13]:
my_array3=np.linspace(0,10,5) #Creates an array of 5 evenly spaced numbers from 0 to 10
print(my_array3)
my_array4=np.linspace(0,1,10)
print(my_array4)

[ 0.   2.5  5.   7.5 10. ]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [14]:
myarray7=np.eye(6) #Creates a 6x6 identity matrix
print(myarray7)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [15]:
# Creating a 1D NumPy array
arr_1D=np.array([10,20,30,40,50,60,70])

In [16]:
# Accessing elements in a 1D NumPy array using positive and negative indexing
print(arr_1D[3]) # Returns the element at zero-based index 3
print(arr_1D[-1]) # Returns the last element of the array
print(arr_1D[-3]) # Returns the third element from the end

40
70
50


In [17]:
# 1D Array Slicing Syntax: [start : stop : step]
# Note: 'stop' index is always excluded (upper bound is not included)
print(arr_1D[1:5])  # Output: [20 30 40 50] | Slices from index 1 up to (excluding) index 5
print(arr_1D[:5])   # Output: [10 20 30 40 50] | Slices from index 0 up to (excluding) index 5
print(arr_1D[4:])   # Output: [50 60 70] | Slices from index 4 all the way to the end
print(arr_1D[::])   # Output: [10 20 30 40 50 60 70] | Returns a complete copy/view of the entire array
print(arr_1D[1:6:3]) # Output: [20 50] | Slices from index 1 to 6 with a step size of 3
print(arr_1D[::2])  # Output: [10 30 50 70] | Select every 2nd element from start to the end

[20 30 40 50]
[10 20 30 40 50]
[50 60 70]
[10 20 30 40 50 60 70]
[20 50]
[10 30 50 70]


In [18]:
# Creating a 2D NumPy array
arr_2D=np.array([
                    [10,20,30],
                    [40,50,60],
                    [70,80,90]
                ])
print(arr_2D)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [19]:
# 2D Array Slicing Syntax: name_array[row_slice, col_slice]
# Note: Syntax follows [start:stop:step]. Upper bound ('stop') is always excluded.
print(arr_2D[1, 2]) # Accessing row index 1, column index 2
print(arr_2D[0,1])  # Accessing row index 0, column index 1
print(arr_2D[:,1])  # Extracting all rows from column index 1 (the entire 2nd column)
print(arr_2D[:,0:2]) # Extracting all rows for column indices 0 and 1 (first 2 columns)
print(arr_2D[0:2,0:2]) # Extracting a sub-matrix: rows 0 and 1, columns 0 and 1 (top-left 2x2 section)

60
20
[20 50 80]
[[10 20]
 [40 50]
 [70 80]]
[[10 20]
 [40 50]]


In [20]:
# Accessing elements using Boolean Masking (requires square brackets)
print(arr_2D[arr_2D>15]) # Returns elements greater than 15
print(arr_2D[arr_2D<10]) # Returns elements lesser than 10
print(arr_2D[arr_2D>=50]) # Returns elements greater or equals to 50

[20 30 40 50 60 70 80 90]
[]
[50 60 70 80 90]


In [21]:
# Creating a 3D NumPy array
arr_3D=np.array([
        [
            [12,52,33],
            [40,5,16]
        ],
        [
            [18,9,12],
            [1,37,44]
        ],
        [
            [4,29,53],
            [31,90,78]
        ]

])

In [22]:
#Accessing elements of 3D NumPy array
print(arr_3D[0]) # Accessing the entire 1st matrix (depth index 0)
print(arr_3D[2]) # Accessing the entire 3rd matrix (depth index 2)
print(arr_3D[1,1]) # Extracting a specific row: 2nd matrix (index 1), 2nd row (index 1)
print(arr_3D[0,1,2]) # Accessing a single element: 1st matrix (index 0), 2nd row (index 1), 3rd column

[[12 52 33]
 [40  5 16]]
[[ 4 29 53]
 [31 90 78]]
[ 1 37 44]
16


In [23]:
# NumPy Data Types (dtypes)

# 1. Automatic Type Inference:
# NumPy automatically detects integer input and assigns the default integer type (int64/int32 depending on OS)
array1=np.array([7,11,34])
print("Data Type of array1 ",array1.dtype)

Data Type of array1  int64


In [24]:
# 2. Explicit Type Definition:
# Explicitly specifying the data type to optimize memory usage (32-bit integer).
array2=np.array([1,5,32],dtype=np.int32)
print("Data Type of array2 ",array2.dtype)

Data Type of array2  int32


In [25]:
array3=np.array([1,2,8.5,3.2],dtype=np.float32) # Explicitly creating a floating-point array with 32-bit precision (float32)
print("Data Type of array3 ",array3.dtype)

Data Type of array3  float32


In [26]:
# Precision comparison between 32-bit (float32) and 64-bit (float64) floating-point numbers
array4=np.array([7.1234567891011],dtype=np.float32)
array5=np.array([7.1234567891011],dtype=np.float64)
print("array4 (float32): ",array4) # float32 loses precision after ~7 decimal places
print("array5 (float64): ",array5) # float64 preserves precision up to ~15-17 decimal places

array4 (float32):  [7.123457]
array5 (float64):  [7.12345679]
