# 01_numpy_basics.ipynb

> 💡 **Overview & Core Focus**
> This notebook provides a comprehensive, production-ready reference for foundational **NumPy** concepts. It covers array creation mechanisms, multi-dimensional tensor structures (1D, 2D, 3D), indexing & slicing semantics, a complete **Dtype Registry** (signed/unsigned integers, precision float behavior, Unicode vs. ASCII string truncation, complex numbers, objects, and datetimes), and low-level memory management architecture (**Copy vs. View**).

In [1]:
import numpy as np   #Imports the NumPy library with the 'np' alias

In [2]:
arr=np.array(19) #defines 0D-Skalar array
print(arr)
print(type(arr))
print(arr.ndim) #checks array dimension 

19
<class 'numpy.ndarray'>
0


In [3]:
arr1=np.array([21,13,8,4,9]) #Creates a 1D NumPy array
print(arr1)
print(arr1.ndim) #checks array dimension 

[21 13  8  4  9]
1


In [4]:
arr2=np.array([[1,2,3],[4,5,6]]) #Creates a 2D-Matrix NumPy array (2*3)
print(arr2)
print(type(arr2))
print(arr2.ndim) #checks array dimension 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [5]:
arr3=np.array([[[1],[2]],[[1],[2]],[[1],[2]]]) #Creates a 3D-Tensor NumPy array 
print(arr3)
print(arr3.ndim) #checks array dimension 

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]]
3


In [6]:
arr4=np.array([4,5,6,7],ndmin=7) #Creates a NumPy array with a minimum of 7 dimension
print("Number of Dimension",arr4.ndim)
print(arr4)

Number of Dimension 7
[[[[[[[4 5 6 7]]]]]]]


In [7]:
my_array=np.arange(1,20,3) # Creates an array of numbers from 1 up to 20 with a step size of 3
print(my_array)

[ 1  4  7 10 13 16 19]


In [8]:
my_array1=np.zeros((2,4)) # Creates a 2x4 matrix filled with zeros
print(my_array1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
my_array2=np.ones((4,3)) # Creates a 4x3 matrix filled with ones
print(my_array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
my_array5=np.full((2,3),5) # Creates a 2x3 matrix filled with the value 5
print(my_array5)

[[5 5 5]
 [5 5 5]]


In [11]:
my_array6=np.empty((2,2)) # Creates an uninitialized 2x2 matrix with random memory values
print(my_array6)

[[0. 0.]
 [0. 0.]]


In [12]:
my_array3=np.linspace(0,10,5) #Creates an array of 5 evenly spaced numbers from 0 to 10
print(my_array3)
my_array4=np.linspace(0,1,10)
print(my_array4)

[ 0.   2.5  5.   7.5 10. ]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [13]:
myarray7=np.eye(6) #Creates a 6x6 identity matrix
print(myarray7)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [14]:
# Creating a 1D NumPy array
arr_1D=np.array([10,20,30,40,50,60,70])

In [15]:
# Accessing elements in a 1D NumPy array using positive and negative indexing
print(arr_1D[3]) # Returns the element at zero-based index 3
print(arr_1D[-1]) # Returns the last element of the array
print(arr_1D[-3]) # Returns the third element from the end

40
70
50


In [16]:
# 1D Array Slicing Syntax: [start : stop : step]
# Note: 'stop' index is always excluded (upper bound is not included)
print(arr_1D[1:5])   # Slices from index 1 up to (excluding) index 5
print(arr_1D[:5])    # Slices from index 0 up to (excluding) index 5
print(arr_1D[4:])    # Slices from index 4 all the way to the end
print(arr_1D[::])    # Returns a complete copy/view of the entire array
print(arr_1D[1:6:3]) # Slices from index 1 to 6 with a step size of 3
print(arr_1D[::2])   # Select every 2nd element from start to the end

[20 30 40 50]
[10 20 30 40 50]
[50 60 70]
[10 20 30 40 50 60 70]
[20 50]
[10 30 50 70]


In [17]:
# Creating a 2D NumPy array
arr_2D=np.array([
                    [10,20,30],
                    [40,50,60],
                    [70,80,90]
                ])
print(arr_2D)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
# 2D Array Slicing Syntax: name_array[row_slice, col_slice]
# Note: Syntax follows [start:stop:step]. Upper bound ('stop') is always excluded.
print(arr_2D[1, 2]) # Accessing row index 1, column index 2
print(arr_2D[0,1])  # Accessing row index 0, column index 1
print(arr_2D[:,1])  # Extracting all rows from column index 1 (the entire 2nd column)
print(arr_2D[:,0:2]) # Extracting all rows for column indices 0 and 1 (first 2 columns)
print(arr_2D[0:2,0:2]) # Extracting a sub-matrix: rows 0 and 1, columns 0 and 1 (top-left 2x2 section)

60
20
[20 50 80]
[[10 20]
 [40 50]
 [70 80]]
[[10 20]
 [40 50]]


In [19]:
# Accessing elements using Boolean Masking (requires square brackets)
print(arr_2D[arr_2D>15]) # Returns elements greater than 15
print(arr_2D[arr_2D<10]) # Returns elements lesser than 10
print(arr_2D[arr_2D>=50]) # Returns elements greater or equals to 50

[20 30 40 50 60 70 80 90]
[]
[50 60 70 80 90]


In [20]:
# Creating a 3D NumPy array
arr_3D=np.array([
        [
            [12,52,33],
            [40,5,16]
        ],
        [
            [18,9,12],
            [1,37,44]
        ],
        [
            [4,29,53],
            [31,90,78]
        ]

])

In [21]:
#Accessing elements of 3D NumPy array
print(arr_3D[0]) # Accessing the entire 1st matrix (depth index 0)
print(arr_3D[2]) # Accessing the entire 3rd matrix (depth index 2)
print(arr_3D[1,1]) # Extracting a specific row: 2nd matrix (index 1), 2nd row (index 1)
print(arr_3D[0,1,2]) # Accessing a single element: 1st matrix (index 0), 2nd row (index 1), 3rd column

[[12 52 33]
 [40  5 16]]
[[ 4 29 53]
 [31 90 78]]
[ 1 37 44]
16


In [22]:
# NumPy Data Types (dtypes)

# 1. Automatic Type Inference:
# NumPy automatically detects integer input and assigns the default integer type (int64/int32 depending on OS)
array1=np.array([7,11,34])
print("Data Type of array1 ",array1.dtype)

Data Type of array1  int64


In [23]:
# 2. Explicit Type Definition:
# Explicitly specifying the data type to optimize memory usage (32-bit integer).
array2=np.array([1,5,32],dtype=np.int32)
print("Data Type of array2 ",array2.dtype)

Data Type of array2  int32


In [24]:
array3=np.array([1,2,8.5,3.2],dtype=np.float32) # Explicitly creating a floating-point array with 32-bit precision (float32)
print("Data Type of array3 ",array3.dtype)

Data Type of array3  float32


In [25]:
# Precision comparison between 32-bit (float32) and 64-bit (float64) floating-point numbers
array4=np.array([7.1234567891011],dtype=np.float32)
array5=np.array([7.1234567891011],dtype=np.float64)
print("array4 (float32): ",array4) # float32 loses precision after ~7 decimal places
print("array5 (float64): ",array5) # float64 preserves precision up to ~15-17 decimal places

array4 (float32):  [7.123457]
array5 (float64):  [7.12345679]


> 💡 **Cheat Sheet: NumPy String Data Type Codes (`dtype`)**
> - `'i'` / `'i4'` / `'i8'`: **Signed Integer** (`int32` / `int64` - default 4 or 8 bytes)
> - `'u2'` / `'u4'`: **Unsigned Integer** (`uint16`: 0–65,535 / `uint32`: 0–4,294,967,295)
> - `'f4'` / `'f8'`: **Floating-Point** (`float32` / `float64`)
> - `'S'`: **Fixed-Length Byte String** (ASCII characters only, e.g., `'S5'`)
> - `'U'` / `'U1'`..`'U5'`: **Unicode String** (Supports international/special characters)
> - `'b'`: **Boolean Aliased Integer** (`int8` representation storing `0` / `1`)
> - `'c8'` / `'c16'`: **Complex Numbers** (`complex64`: two 32-bit floats / `complex128`: two 64-bit floats)
> - `'object'`: **Generic Python Object** (Holds heterogeneous data types/references)
> - `'M8[D]'`: **Datetime** (`datetime64[D]` with day-level precision)

In [26]:
# Short-code data type representation for signed 32-bit integer (default 'i' maps to int32)
array6=np.array([7,19,23,45],dtype="i")
print(array6.dtype)                       # Output:int32
# Defining signed integer with explicit byte size: 'i4' means 4 bytes (4 * 8 = 32 bits)
array7=np.array([7,19,81,41],dtype="i4")
print(array7.dtype)                       # Output:int32
# Defining signed integer with explicit byte size: 'i8' means 8 bytes (8 * 8 = 64 bits)
array8=np.array([7,19,81,41],dtype="i8")
print(array8.dtype)                       # Output:int64


int32
int32
int64


> 💡 **Key Concept: Floating-Point Precision (`f4` vs `f8`)**
> - **`f4` (`float32`):** Uses 4 bytes (32 bits) of memory. It provides about **6 to 7 decimal digits** of precision. Any extra digits are rounded or truncated.
> - **`f8` (`float64`):** Uses 8 bytes (64 bits) of memory. It provides **15 to 17 decimal digits** of precision and is the default floating-point type in Python/NumPy.

In [27]:
# Single precision float (32-bit / 4 bytes): Truncates digits due to lower precision (~6-7 decimal places)
array9=np.array([1.54377777777777,2.7654444444],dtype="f4") 
print(array9.dtype)  # Output: float32
print(array9)        # Output: [1.5437778 2.7654445]
# Double precision float (64-bit / 8 bytes): Retains high precision (~15-17 decimal places)
array10=np.array([1.54377777777777,2.765444444],dtype="f8") 
print(array10.dtype)  # Output: float64
print(array10)        # Output: [1.54377778 2.76544444]

float32
[1.5437778 2.7654445]
float64
[1.54377778 2.76544444]


> 📌 **Takeaway:** `float32` uses **50% less memory** and is preferred in Deep Learning (GPUs), while `float64` is essential for precise scientific computing.

In [28]:
arr11=np.array([100,200,300],dtype="u2")
print(arr11)
print(arr11.dtype) # Output: uint16
arr12=np.array([100,200,300],dtype="u4")
print(arr12)
print(arr12.dtype) # Output: uint32

[100 200 300]
uint16
[100 200 300]
uint32


> 📌 **Takeaway & Application:**
> Unsigned integers are heavily used in **Image Processing** (e.g., RGB pixel values from $0$ to $255$ use `uint8` or `'u1'`) to optimize memory. Never store negative numbers or subtraction results in unsigned arrays without checking for underflow!

> 💡 **Key Concept: Unicode Strings (`'U'`) vs. Byte Strings (`'S'`)**
> - **Unicode (`'U'`):** Supports all international and special characters (like non-ASCII characters: `ç`, `ğ`, `ı`, `ö`, `ş`, `ü`). It uses variable UTF-8/UTF-32 encodings internally.
> - **Byte Strings (`'S'`):** Strictly expects ASCII characters. Non-ASCII raw bytes (e.g., `b'çilek'`) will raise a `SyntaxError: bytes can only contain ASCII literal characters` at syntax level.
> - **Dynamic Length Mapping:** `dtype="U"` automatically scales to the maximum string length in the array (e.g., `'çilek'` has 5 characters $\rightarrow$ `<U5`).

In [29]:
# Byte strings with automatic fixed-length allocation (longest item 'python' has 6 characters)
arr12=np.array([b'hello',b'python'],dtype="S")
print(arr12)       # Output: [b'hello' b'python']
print(arr12.dtype) # Output: |S6

# Specifying 'S5' forces a 5-byte limit, truncating 'python' to 'pytho':
arr12_truncated = np.array([b'hello', b'python'], dtype="S5")
print(arr12_truncated) # Output: [b'hello' b'pytho']

[b'hello' b'python']
|S6
[b'hello' b'pytho']


In [30]:
# Unicode string array containing special characters
arr13=np.array(['çilek','üzüm'], dtype="U")
print(arr13)
print(arr12.dtype)

#arr13_error=np.array([b'çilek',b'üzüm'], dtype="S")
# SyntaxError: bytes can only contain ASCII literal characters.

['çilek' 'üzüm']
|S6


> 📌 **Takeaway & Best Practice:**
> Always use Unicode strings (`dtype="U"` or default `str`) when processing natural language, user-generated text, or non-English datasets to avoid character encoding errors and syntax crashes.

In [31]:
# Signed 8-bit integer/boolean type code 'b' (int8 storing 1s and 0s for boolean values)
arr_b=np.array([True,False,True],dtype="b")
print(arr_b)        # Output: [1 0 1]
print(arr_b.dtype)  # Output: int8

[1 0 1]
int8


In [32]:
# Single precision complex numbers ('c8' / complex64: two 32-bit floats for real and imaginary parts)
arr_c1=np.array([1+4j,3+7j],dtype="c8")
print(arr_c1)
print(arr_c1.dtype) # Output: complex64
# Double precision complex numbers ('c16' / complex128: two 64-bit floats for real and imaginary parts)
arr_c2=np.array([1+4j,3+7j],dtype="c16")
print(arr_c2)
print(arr_c2.dtype) # Output: complex128

[1.+4.j 3.+7.j]
complex64
[1.+4.j 3.+7.j]
complex128


In [33]:
# Object data type ('object' / 'O'): Holds heterogeneous Python objects (integers, strings, floats, lists) via references
arr_o=np.array([7,"python",19.21,[7,19,6]],dtype="object")
print(arr_o)
print(arr_o.dtype) # Output: object

[7 'python' 19.21 list([7, 19, 6])]
object


In [34]:
# Datetime data type ('M8[D]' / datetime64[D]): Stores dates with day-level precision using 64-bit integers
arr_dt=np.array(["2009-09-19","2020-01-10"],dtype="M8[D]")
print(arr_dt)
print(arr_dt.dtype) # Output: datetime64[D]

['2009-09-19' '2020-01-10']
datetime64[D]


> 💡 **Key Concept: Memory Architecture — `Copy` vs. `View`**
> - **Memory Ownership & Independence:**
>   - **`Copy` (`.copy()`):** Allocates an entirely new, independent memory block. Changes made to the copy do **not** affect the original array, and vice versa.
>   - **`View` (`.view()` or Slicing):** Creates a new array object that points to the **same underlying memory buffer** as the original array. Modifying elements in a view directly mutates the source dataset.
> - **Inspection via `.base` Attribute:**
>   - **`copy_arr.base` $\rightarrow$ `None`:** Indicates the array owns its memory buffer (it is a standalone Copy).
>   - **`view_arr.base` $\rightarrow$ `original_array`:** Points back to the parent array object, confirming it shares memory with another array (it is a View).

In [35]:
original_array=np.array([7,19,6,83,71])
copy_array=original_array.copy() # Create an explicit copy in independent memory
original_array[0]=11      # Modify element in the original array
print(original_array)     # Print original array to confirm modification
print(copy_array)         # Print copy array to verify data independence
# Check memory ownership (.base is None for copies)
print(copy_array.base)    # Output: None

[11 19  6 83 71]
[ 7 19  6 83 71]
None


In [36]:
original_arr=np.array([11,22,33,44])
copy_arr=original_arr.view() # Create a view pointing to the same memory buffer
original_arr[1]=99       # Modify element in the original array
print(original_arr)      # Print original array to see updated values
print(copy_arr)          # Print view array to verify shared memory mutation
# Check memory ownership (.base points back to the original array)
print(copy_arr.base)      # Output: [11 99 33 44]

[11 99 33 44]
[11 99 33 44]
[11 99 33 44]


> 📌 **Takeaway & Best Practices: `Copy` vs. `View`**
> - **Performance vs. Safety Trade-off:**
>   - Use **`View`** (or standard slicing) for ultra-fast operations on massive datasets, as it avoids memory allocation and data copying.
>   - Use **`Copy`** (`.copy()`) whenever you need to filter, transform, or overwrite values without risking unintended side effects on your primary source data.
> - **Debugging Rule of Thumb:** If an array's values change unexpectedly during pipeline execution, inspect `.base` to verify whether you are accidentally modifying a shared memory buffer.

> 💡 **Key Concept: Array Shape Across All Dimensions (`.shape`)**
> - **Dimensional Hierarchy:** The `.shape` attribute returns a tuple of integers defining the length of the array along each of its axes (dimensions).
> - **1D Vector `(N,)`:** Has 1 axis (Axis 0). Represents a flat sequence of $N$ elements. Returns a single-element tuple with a trailing comma.
> - **2D Matrix `(M, N)`:** Has 2 axes (Axis 0 = Rows, Axis 1 = Columns). Represents a standard tabular structure with $M$ rows and $N$ columns.
> - **3D Tensor `(D, M, N)`:** Has 3 axes (Axis 0 = Depth/Blocks, Axis 1 = Rows, Axis 2 = Columns). Represents a collection or stack of $D$ two-dimensional matrices.
> - **N-Dimensional Tensor `(D1, D2, ..., Dn)`:** Generalizes to $n$ dimensions. The total number of elements in any array is always the product of all elements in its shape tuple ($\prod Shape = Size$).

In [37]:
arr_1d=np.array([7,19,6,42,3])
# Inspect array dimensions (returns a tuple)
print(arr_1d.shape)    # Output: (5,)
# Inspect 2D matrix dimensions (rows, columns)
arr_2d=np.array([
                [1,2],
                [3,4],
                [5,6]
                ])
print(arr_2d.shape)    # Output: (3, 2)
arr_3d=np.array([
                    [
                        [11,2],
                        [38,4],
                        [5,60]
                    ],
                    [
                        [10,23],
                        [85,92],
                        [7,11]
                    ],
                    [
                        [4,8],
                        [13,5],
                        [21,52]
                    ]
                ])
# Inspect 3D tensor dimensions (matrices/depth, rows, columns)
print(arr_3d.shape)     # Output: (3, 3, 2)

(5,)
(3, 2)
(3, 3, 2)
