In [1]:
# NumPy Basics & Fundamentals

#This notebook covers the core concepts of NumPy, including array creation, multi-dimensional structures, and essential built-in functions.

In [2]:
import numpy as np   #Imports the NumPy library with the 'np' alias

In [3]:
arr=np.array(19) #defines 0D-Skalar array
print(arr)
print(type(arr))
print(arr.ndim) #checks array dimension 

19
<class 'numpy.ndarray'>
0


In [4]:
arr1=np.array([21,13,8,4,9]) #Creates a 1D NumPy array
print(arr1)
print(arr1.ndim) #checks array dimension 

[21 13  8  4  9]
1


In [5]:
arr2=np.array([[1,2,3],[4,5,6]]) #Creates a 2D-Matrix NumPy array (2*3)
print(arr2)
print(type(arr2))
print(arr2.ndim) #checks array dimension 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [6]:
arr3=np.array([[[1],[2]],[[1],[2]],[[1],[2]]]) #Creates a 3D-Tensor NumPy array 
print(arr3)
print(arr3.ndim) #checks array dimension 

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]]
3


In [7]:
arr4=np.array([4,5,6,7],ndmin=7) #Creates a NumPy array with a minimum of 7 dimension
print("Number of Dimension",arr4.ndim)
print(arr4)

Number of Dimension 7
[[[[[[[4 5 6 7]]]]]]]


In [8]:
my_array=np.arange(1,20,3) # Creates an array of numbers from 1 up to 20 with a step size of 3
print(my_array)

[ 1  4  7 10 13 16 19]


In [9]:
my_array1=np.zeros((2,4)) # Creates a 2x4 matrix filled with zeros
print(my_array1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
my_array2=np.ones((4,3)) # Creates a 4x3 matrix filled with ones
print(my_array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
my_array5=np.full((2,3),5) # Creates a 2x3 matrix filled with the value 5
print(my_array5)

[[5 5 5]
 [5 5 5]]


In [12]:
my_array6=np.empty((2,2)) # Creates an uninitialized 2x2 matrix with random memory values
print(my_array6)

[[0. 0.]
 [0. 0.]]


In [13]:
my_array3=np.linspace(0,10,5) #Creates an array of 5 evenly spaced numbers from 0 to 10
print(my_array3)
my_array4=np.linspace(0,1,10)
print(my_array4)

[ 0.   2.5  5.   7.5 10. ]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [14]:
myarray7=np.eye(6) #Creates a 6x6 identity matrix
print(myarray7)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
