# 02. Array Manipulation & Structural Transformations

This notebook covers array reshaping, dimension swapping, flattening operations (`flatten` vs. `ravel`), multidimensional iteration, joining, and splitting techniques in NumPy.

In [1]:
import numpy as np

> 💡 **Key Concept: Reshaping & Automatic Dimension Inference (`-1`)**
> - **Total Element Invariance:** The total number of elements ($\prod shape$) must remain strictly constant before and after reshaping (e.g., $1\times12 = 3\times4 = 2\times2\times3$).
> - **Shared Memory View:** `.reshape()` returns a **view** whenever possible. Modifying the reshaped array will mutate the original array unless explicitly copied.
> - **Automatic Dimension Inference (`-1`):** Passing `-1` as one of the dimension arguments instructs NumPy to automatically calculate that specific axis length based on the remaining dimensions and total element count.
> - **Constraint & Resilience:** You can use `-1` only **once** per `.reshape()` call. It eliminates hardcoded dimension math, making data pipelines resilient to varying batch sizes or input lengths.

In [2]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
new_arr=arr.reshape(4,3) # Reshape the 1D array into a 2D matrix with 4 rows and 3 columns (4x3 = 12 elements)
print("\nReshaped (4x3):\n",new_arr)

# Verify memory ownership (Reference to 01_numpy_basics: .base confirms reshape is a View)
print("Base array (Memory Owner):\n",new_arr.base)

print("\nReshaped (2x6):\n",arr.reshape(2,-1)) # Set rows to 2; '-1' automatically infers the required number of columns (12 / 2 = 6 columns -> 2x6)
print("\nReshaped 3D (3x4x1):\n",arr.reshape(3,4,-1)) # Reshape into a 3D tensor: 3 matrices, 4 rows, and inferred columns (12 / (3*4) = 1 column -> 3x4x1)


Reshaped (4x3):
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Base array (Memory Owner):
 [ 10  20  30  40  50  60  70  80  90 100 110 120]

Reshaped (2x6):
 [[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]

Reshaped 3D (3x4x1):
 [[[ 10]
  [ 20]
  [ 30]
  [ 40]]

 [[ 50]
  [ 60]
  [ 70]
  [ 80]]

 [[ 90]
  [100]
  [110]
  [120]]]


> 📌 **Takeaway:**
> - As established in `01_numpy_basics`, `.reshape()` generates a **View** whenever possible without allocating new memory.
> - Modifying `new_arr` directly mutates `arr` because `new_arr.base` points to `arr`.

In [3]:
arr_2D=np.array([
                    [7,19,6],
                    [8,20,7]
                ])

# 1. Flattening using .reshape(-1): Collapses 2D array into 1D (returns a View)
matrix1=arr_2D.reshape(-1)
print("1D via reshape(-1):",matrix1)

# Memory ownership check: returns the original array, proving matrix1 is a View
print("Memory owner of matrix1 (View check):",matrix1.base)

# 2. Flattening using .flatten(): Collapses 2D array into 1D (always returns a Copy)
matrix2=arr_2D.flatten()
print("\n1D via .flatten():",matrix2)

# Memory ownership check: returns None, proving matrix2 owns its memory (Copy)
print("Memory owner of matrix2 (Copy check):",matrix2.base)

matrix3=arr_2D.ravel()
# 3. Flattening using .ravel(): Collapses 2D array into 1D (returns a View whenever possible)
print("\nFlattening via .ravel()",matrix3)

# Memory ownership check: returns the original array, proving matrix3 is a View
print("\nMemory owner of matrix3 (View check):",matrix3.base)

1D via reshape(-1): [ 7 19  6  8 20  7]
Memory owner of matrix1 (View check): [[ 7 19  6]
 [ 8 20  7]]

1D via .flatten(): [ 7 19  6  8 20  7]
Memory owner of matrix2 (Copy check): None


NameError: name 'matrix3' is not defined

> 📌 **Takeaway:**
> - **`.flatten()`**: Always creates an independent **Copy** in memory (`.base` returns `None`). Safe for non-destructive operations, but costs additional memory allocation.
> - **`.ravel()` & `.reshape(-1)`**: Return a **View** whenever possible (`.base` points to the source array). Highly performance-efficient and memory-friendly for large data pipelines.
> - Always verify memory ownership with `.base` if downstream modifications could inadvertently mutate the original dataset.